desafioTCS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from gerenciamento.views import dashboard

urlpatterns = [
    path('', include('login.urls', namespace='login')),
    path('', dashboard),
    path('dashboard/', include('gerenciamento.urls', namespace='dashboard')),
    path('admin/', admin.site.urls),
]

gerenciamento/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('login/', views.auth_login, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('logout/', views.log_out, name='logout'),
]

gerenciamento/models.py
from django.db import models
# from django.db.models.fields import Datetime
from login.models import User
# from django.contrib.auth.models import User

class Status(models.Model):
    codigo = models.CharField(max_length=10)
    nome = models.CharField(max_length=20)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome
        
class Maquina(models.Model):
    nome = models.CharField(max_length=20)
    status_id = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Evento(models.Model):
    data = models.DateTimeField(null=True)
    status_id = models.ForeignKey(Status, on_delete=models.SET_NULL, null=True)
    maquina_id = models.ForeignKey(Maquina, on_delete=models.SET_NULL, null=True)
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.id} + {self.data} + {self.status_id} + {self.maquina_id}"

gerenciamento/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from .models import Status, Maquina, Evento
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt, csrf_protect
# from django.contrib.auth.models import User
from django_celery_beat.models import PeriodicTask, IntervalSchedule
from login.models import User
import json

@csrf_exempt
@login_required(login_url='/login')
def dashboard(request):
    user = User.objects.filter(id = request.user.id).first()
    if request.method == 'POST':
        codigo = request.POST.get('codigo', False)
        nome = request.POST.get('nome', False)
        method = request.POST.get('_method', False)
        model_class = request.POST.get('_model_class', False)
        class_id = request.POST.get('_id', False)
        period = request.POST.get('period', False)

        if period:
            set_event_period(request, period)

        if model_class == 'status':
            if method == 'PUT':
                atualiza_status(codigo, nome, class_id, request)
            elif method == 'DELETE':
                delete_status(class_id, request)
            else:
                criar_status(codigo, nome, user, request)
        elif model_class == 'maquina':
            if method == 'PUT':
                atualiza_maquina(nome, class_id, request)
            elif method == 'DELETE':
                delete_maquina(class_id, request)
            else:
                criar_maquina(nome, user, request)

    user_id = request.user.id
    all_status = Status.objects.filter(user_id=user_id).all()
    maquinas = Maquina.objects.filter(user_id=user_id).all()
    eventos = Evento.objects.filter(user_id=user_id).all().order_by('-data')[:10]

    return render(request, 'gerenciamento/dashboard.html', {'all_status': all_status, 'maquinas': maquinas, 'eventos': eventos})


def criar_maquina(nome, user, request):
    try:
        Maquina.objects.create(nome=nome, user_id=user)
        messages.add_message(request, messages.SUCCESS, f'Máquina criada com sucesso')
    except:
        messages.add_message(request, messages.WARNING, f'Não foi possível adicionar a Máquina')

def delete_maquina(class_id, request):
    try:
        maquina = Maquina.objects.filter(id=class_id).first()
        maquina.delete()
        messages.add_message(request, messages.SUCCESS, f'Máquina deletada com sucesso')
    except:
        messages.add_message(request, messages.SUCCESS, f'Não foi possível deletar a Máquina')
    
def atualiza_maquina(nome, class_id, request):
    try:
        maquina = Maquina.objects.filter(id=class_id).first()
        maquina.nome = nome
        maquina.save()
        messages.add_message(request, messages.SUCCESS, f'Máquina atualizada com sucesso')
    except:
        messages.add_message(request, messages.SUCCESS, f'Não foi possível atualizar a Máquina')

def criar_status(codigo, nome, user, request):
    try:
        status = Status()
        if codigo_exists(codigo):
            messages.add_message(request, messages.INFO, f'Este código já existe')
        else:
            status.codigo = codigo
            status.nome = nome
            status.user_id = user
            status.save()
            messages.add_message(request, messages.SUCCESS, f'Status criado com sucesso')
    except:
        messages.add_message(request, messages.WARNING, f'Não foi possível adicionar o status')

def atualiza_status(codigo, nome, status_id, request):
    try:
        status = Status.objects.filter(id=status_id).first()

        if nome:
            status.nome = nome
            messages.add_message(request, messages.SUCCESS, f'Nome do status atualizado com sucesso')
            status.save()
        
        if codigo and codigo_exists(codigo):
            messages.add_message(request, messages.WARNING, f'Código já existente')
        elif codigo:
            status.codigo = codigo
            status.save()
            messages.add_message(request, messages.SUCCESS, f'Código atualizado com sucesso')
    except:
        messages.add_message(request, messages.WARNING, f'Não foi possível alterar o status')

def delete_status(status_id, request):
    try:
        status = Status.objects.filter(id=status_id)

        status.delete()
        messages.add_message(request, messages.SUCCESS, f'Status deletado com sucesso')
    except:
        messages.add_message(request, messages.SUCCESS, f'Não foi possível deletar o status')

def codigo_exists(codigo):
    return Status.objects.filter(codigo=codigo).exists()

def set_event_period(request, period):
    user = User.objects.filter(id=request.user.id).first()
    schedule, created = IntervalSchedule.objects.get_or_create(
    every=period,
    period=IntervalSchedule.MINUTES)

    try:
        PeriodicTask.objects.filter(id=user.periodic_task_id.id).first().delete()
    except:
        pass
    finally:
        pd = PeriodicTask.objects.create(interval=schedule,
            name=f'{request.user.username} change machine status',
            task='gerenciamento.tasks.mudando_status_maquinas',
            # args=json.dumps(['one', 'two']),
            args=json.dumps([user.id],)
            # kwargs=json.dumps()
        )

        pd.save()
        user.periodic_task_id = pd
        user.save()

gerenciamento/templates/gerenciamento/dashboard.html
{% extends 'base.html' %}
{% block title %} Dashboard {% endblock %}
{% load static %}
{% block style %}
<style>
    * {
        list-style-type: none
    }
</style>
{% endblock %}

{% block body %}

<nav class="navbar navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="https://github.com/regyeduardo" target="_blank">Regy</a>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown"
            aria-expanded="false">
            {{ user }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{% url 'login:logout' %}">Sair</a>
            </div>
        </li>
    </div>
</nav>

<div class="container">

    {% if messages %}
        {% for message in messages %}
            {% if message.level %}
                <div class="alert alert-{{ message.tags }} " role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endif %}
        {% endfor %}
    {% endif %}
    <div class="row">
        <div class="col-sm">
            <div class="card">
                <div class="card-body">
                    <h5>Frequência de Eventos</h5>
                    <form class="form-row" action="" method="post">
                        <div class="col">
                            <!-- <div class="form-group"> -->
                                <input type="number" name="period" min=0 max=55 value="0" required>
                            <!-- </div> -->
                            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Definir</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="row mb-4">
        <div class="col-sm">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Status</h5>
    
                    {% if all_status %}
                    <form action="" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_model_class" value="status">
                        <div class="table-responsive">
                            <table class="table table-borderless table-hover table-sm">
                                <caption>
                                    <button class="btn btn-primary botao-criar botao-caption status">Criar</button>
                                </caption>
                                <thead>
                                    <tr>
                                        <th scope="col">Código</th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                    {% for status in all_status %}
                                    <tr>
                                        <input type="hidden" class="hidden_id" name="_id" value="{{ status.id }}" disabled>
                                        <td>
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="codigo"
                                                    curvalue="{{ status.codigo }}" value="{{ status.codigo }}"
                                                    disabled="">
                                                <span class="input-group-append">
                                                    <i class="input-group-text bi bi-pencil-square"></i>
                                                </span>
                                            </div>
                                        </td>
    
                                        <td>
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="nome"
                                                    curvalue="{{ status.nome }}" value="{{ status.nome }}" disabled>
                                                <span class="input-group-append">
                                                    <i class="input-group-text bi bi-pencil-square"></i>
                                                </span>
                                            </div>
                                        </td>
    
                                        <td>
                                            <button class="btn btn-danger botao-apagar w-100 {{ status.id }}">Apagar</button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </form>
                    {% else %}
                    <form action="" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_model_class" value="status">
                        <div class="table-responsive">
                            <table class="table table-borderless table-hover table-sm">
                                <caption>
                                    <button class="btn btn-primary botao-criar botao-caption ml-3 status">Criar</button>
                                </caption>
                                <thead>
                                    <tr>
                                        <th scope="col">Código</th>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <p class="lead vazio text-center">
                                        Não há nenhum status.
                                    </p>
                                </tbody>
                            </table>
                        </div>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-sm">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Máquinas</h5>
    
                    {% if maquinas %}
                    <form action="" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_model_class" value="maquina">
                        <div class="table-responsive">
                            <table class="table table-borderless table-hover table-sm">
                                <caption>
                                    <button class="btn btn-primary botao-criar botao-caption maquina">Criar</button>
                                </caption>
                                <thead>
                                    <tr>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                    {% for maquina in maquinas %}
                                    <tr>
                                        <input type="hidden" class="hidden_id" name="_id" value="{{ maquina.id }}" disabled>
                                        <td>
                                            <div class="input-group">
                                                <input type="text" class="form-control" name="nome"
                                                    curvalue="{{ maquina.nome }}" value="{{ maquina.nome }}"
                                                    disabled="">
                                                <span class="input-group-append">
                                                    <i class="input-group-text bi bi-pencil-square"></i>
                                                </span>
                                            </div>
                                        </td>
    
                                        <td>
                                                <input type="text" class="form-control" value="{{ maquina.status_id }}" disabled>
                                        </td>
    
                                        <td>
                                            <button class="btn btn-danger botao-apagar w-100 {{ maquina.status_id }}">Apagar</button>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </form>
                    {% else %}
                    <form action="" method="post">
                        <input type="hidden" name="_method" value="PUT">
                        <input type="hidden" name="_model_class" value="maquina">
                        <div class="table-responsive">
                            <table class="table table-borderless table-hover table-sm">
                                <caption>
                                    <button class="btn btn-primary botao-criar botao-caption maquina ml-3">Criar</button>
                                </caption>
                                <thead>
                                    <tr>
                                        <th scope="col">Nome</th>
                                        <th scope="col">Status</th>
                                        <th scope="col">Ação</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <p class="lead vazio text-center">
                                        Não há nenhuma máquina.
                                    </p>
                                </tbody>
                            </table>
                        </div>
                    </form>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        <div class="col-sm">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Eventos</h5>
    
                    {% if eventos %}
                        <div class="table-responsive">
                            <table class="table table-borderless table-hover table-sm">
                                <thead>
                                    <tr>
                                        <th scope="col">Status</th>
                                        <th scope="col">Máquina</th>
                                        <th scope="col">Data</th>
                                    </tr>
                                </thead>
                                <tbody>
    
                                    {% for evento in eventos %}
                                    <tr>
                                        <td>
                                           {{ evento.status_id }}
                                        </td>
    
                                        <td>
                                            {{ evento.maquina_id }}
                                        </td>
    
                                        <td>
                                            {{ evento.data }}
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </form>
                    {% else %}
                    <p class="lead vazio text-center">
                        Não há eventos.
                    </p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'gerenciamento/script.js' %}"></script>
<script>
    window.addEventListener('keydown', function (e) { if (e.keyIdentifier == 'U+000A' || e.keyIdentifier == 'Enter' || e.keyCode == 13) { if (e.target.nodeName === 'INPUT' && e.target.type !== 'textarea') { e.preventDefault(); return false; } } }, true);
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
{% endblock %}