desafioTCS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from gerenciamento.views import dashboard

urlpatterns = [
    path('', include('login.urls', namespace='login')),
    path('', dashboard),
    path('dashboard/', include('gerenciamento.urls', namespace='dashboard')),
    path('admin/', admin.site.urls),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'
urlpatterns = [
    path('login/', views.auth_login, name='login'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('logout/', views.log_out, name='logout'),
]

login/models.py
from django.contrib.auth.models import AbstractUser
from django_celery_beat.models import PeriodicTask
from django.db import models

class User(AbstractUser):
    periodic_task_id = models.OneToOneField(PeriodicTask, on_delete=models.SET_NULL, null=True)

login/forms.py
from django import forms


class Cadastro(forms.Form):
    username = forms.CharField(label='username', max_length=100, required=True)
    senha = forms.CharField(label="senha", max_length=20, required=True)

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.urls import reverse
from django.contrib import messages
# from django.contrib.auth.models import User
from .models import User

@csrf_exempt
def auth_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']


        user = authenticate(username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('dashboard:dashboard'))
        # elif not user.is_active:
        #     messages.add_message(request, 30, 'Sua conta não esta ativa.')
        else:
            messages.add_message(request, 20, 'Usuário ou senha inválidos')

    return render(request, 'login/login.html', {})

@csrf_exempt
def cadastro(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        if username:
            if not username_exists(username):
                User.objects.create_user(username=username, password=password)
                messages.success(request, f"Usuário {username} criado com sucesso")

                return redirect('login:login')
            else:
                messages.add_message(request, 20, 'Este usuário já existe')
        else:
            messages.add_message(request, 30, 'Necessita especificar um nome de usuário')

    return render(request, 'login/cadastro.html', {})

def log_out(request):
    logout(request)
    messages.success(request, "Deslogado com sucesso")
    return HttpResponseRedirect(reverse('login:login'))


def username_exists(username):
    return User.objects.filter(username=username).exists()

login/templates/login/cadastro.html
{% extends 'base_form.html' %}
{% block title %} Cadastro {% endblock %}


{% block form-action %} /cadastro/ {% endblock  %}

{% block botao-cadastro-login %}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}

    <button type="submit" class="btn btn-warning">Cadastrar</button>
    {% if messages %}
        {% for message in messages %}
            {% if message.level %}
            <div class="alert alert-{{ message.tags }} mt-4 mb-4" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
        {% endfor %}
    {% endif %}
{% endblock %}


{% block form-login %}
<div class="link-login mt-4 mb-4">
    <a href="{% url 'login:login' %}" class="">Efetue login caso já tenha conta</a>
</div>
{% endblock %}

login/templates/login/login.html
{% extends 'base_form.html' %}
{% block title %} Login {% endblock %}

{% block form-action %} /login/ {% endblock %}

{% block botao-cadastro-login %}

    {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}

    <button type="submit" class="btn btn-warning">Entrar</button>
    {% if messages %}
        {% for message in messages %}
            {% if message.level %}
                <div class="alert alert-{{ message.tags }} mt-4 mb-4" role="alert">
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
             {% endif %}

        {% endfor %}
    {% endif %}
{% endblock %}


{% block form-login %}
<div class="link-login mt-4 mb-4">
    <a href="{% url 'login:cadastro' %}" class="">Cadastre-se caso não tenha conta</a>
</div>
{% endblock %}